import type { Metadata } from "next";
import "./globals.css";
import 'katex/dist/katex.min.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Header } from "@/components/Header";
import { AnimatedBackground } from "@/components/AnimatedBackground";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className="min-h-screen font-mono tracking-tight selection:bg-primary selection:text-primary-foreground">
        <AnimatedBackground />
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
